# Generated by Django 3.2.15 on 2022-09-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0034_auto_20220714_0937"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="max_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="min_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="step_size",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="question",
            name="widget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SLINE", "Single line text"),
                    ("MLINE", "Multi line text"),
                    ("CHBOX", "Checkboxes"),
                    ("DDOWN", "Dropdown"),
                    ("RADIO", "Radio buttons"),
                    ("SLIDE", "Slider"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("STXT", "Single line text"),
                    ("MTXT", "Multi line text"),
                    ("BOOL", "Bool"),
                    ("NUMB", "Number"),
                    ("HEAD", "Heading"),
                    ("2DBB", "2D bounding box"),
                    ("M2DB", "Multiple 2D bounding boxes"),
                    ("DIST", "Distance measurement"),
                    ("MDIS", "Multiple distance measurements"),
                    ("POIN", "Point"),
                    ("MPOI", "Multiple points"),
                    ("POLY", "Polygon"),
                    ("MPOL", "Multiple polygons"),
                    ("CHOI", "Choice"),
                    ("MCHO", "Multiple choice"),
                    ("MCHD", "Multiple choice dropdown"),
                    ("MASK", "Mask"),
                    ("LINE", "Line"),
                    ("MLIN", "Multiple lines"),
                    ("ANGL", "Angle"),
                    ("MANG", "Multiple angles"),
                    ("TXT", "Text"),
                    ("MCHC", "Multichoice"),
                ],
                default="STXT",
                max_length=4,
            ),
        ),
    ]
